name: pt_baseline_deeplab_mobilenet_bs16
mode: train
data_dir: /data/datasets/
ckpt: null
dataset: cityscapes
size: 769
num_gpus: 2

model: deeplab_mobilenet
pretrained: True
model_clip: false
nan: True

loss: ce
grad_clip: null
epochs: 100
batch_size: 16
lr: 0.01
wd: 1e-4
scheduler: poly
optimizer: sgd

error_model: block
inject_p: 0.0
inject_epoch: 0

seed: 0
comment: test
