name: clip_mobilenet_pt
mode: train
data_dir: /work/tatommasi/silvia/leonardo/datasets/
ckpt: null
dataset: cityscapes
size: 769
num_gpus: 1

model: deeplab_mobilenet
pretrained: True
model_clip: True
nan: True

loss: ce
grad_clip: null
epochs: 100
batch_size: 16
lr: 0.01
wd: 1e-4
scheduler: poly
optimizer: sgd

error_model: block
inject_p: 0.0
inject_epoch: 0

seed: 0
comment: test
